# Generated by Django 3.2.3 on 2021-10-05 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='iframe_detail',
            field=models.TextField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
