# Generated by Django 3.2.3 on 2021-10-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_iframe_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='iframe_detail',
            new_name='gform_link',
        ),
    ]
